In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df=pd.read_csv('Jobs.csv')
df.head(5)

,job_title,company,job_location,job_link,first_seen,search_city,search_country,job level,job_type,job_summary,job_skills
0,"Data Analyst-SQL, Tableau",Zortech Solutions,"Mountain View, CA",https://www.linkedin.com/jobs/data-analyst-jobs,2023-12-20,Bloomington,United States,Associate,Onsite,NaN,NaN
1,Market Research & Insights Analyst,Indiana University Foundation,"Bloomington, IN",https://www.linkedin.com/jobs/view/market-rese...,2023-12-20,Bloomington,United States,Mid senior,Onsite,Company Description\nAre you a high-performer ...,"Data analysis, Market research, Survey develop..."
2,Business Systems Analyst `1,Cook Medical,"Bloomington, IN",https://www.linkedin.com/jobs/view/business-sy...,2023-12-20,Bloomington,United States,Mid senior,Onsite,Overview\nThe Business Systems Analyst 1 perfo...,"Business Analysis, Technical Writing, Software..."
3,Senior VAT and Indirect Tax Analyst,Epic,"Bloomington, IN",https://www.linkedin.com/jobs/view/senior-vat-...,2023-12-20,Bloomington,United States,Mid senior,Onsite,We're looking for an experienced tax professio...,"Accounting, Finance, VAT/GST tax regimes, US a..."
4,Senior HRIS Analyst (Timekeeping and Payroll),Nordson Corporation,Greater Bloomington Area,https://www.linkedin.com/jobs/view/senior-hris...,2023-12-20,Bloomington,United States,Mid senior,Remote,Collaboration drives Nordson’s success as a ma...,"Workday HCM, UKG Dimensions, Ceridian Dayforce..."

In [3]:
df.tail(5)

,job_title,company,job_location,job_link,first_seen,search_city,search_country,job level,job_type,job_summary,job_skills
12889,Business Operations Analyst,LMI Aerospace - A Member of the Sonaca Group,"Washington, MO",https://www.linkedin.com/jobs/view/business-op...,2023-12-20,Atchison,United States,Mid senior,Onsite,Who Are We\nSonaca North America\nis driven by...,"Data Analysis, Business Intelligence, Reportin..."
12890,Senior Military Analyst,Trideum Corporation,"Leavenworth, KS",https://www.linkedin.com/jobs/view/senior-mili...,2023-12-20,Atchison,United States,Mid senior,Onsite,"Full-time\nFort Leavenworth, KS\nAbout Us\nTri...","Microsoft Office Suite, Outlook, Word, Excel, ..."
12891,Senior Military Systems Analyst to support the...,"Nemean Solutions, LLC","Leavenworth, KS",https://www.linkedin.com/jobs/view/senior-mili...,2023-12-20,Atchison,United States,Mid senior,Onsite,"Nemean Solutions, LLC is looking for a Senior ...","C2 Warfighting Function, Echelons Above Brigad..."
12892,Senior Military Analyst to support the Mission...,"Nemean Solutions, LLC","Leavenworth, KS",https://www.linkedin.com/jobs/view/senior-mili...,2023-12-20,Atchison,United States,Mid senior,Onsite,"Nemean Solutions, LLC is looking for a Senior ...","Military Analyst, Command and Control (C2), Wa..."
12893,Senior Military Systems Analyst,Trideum Corporation,"Leavenworth, KS",https://www.linkedin.com/jobs/view/senior-mili...,2023-12-20,Atchison,United States,Mid senior,Onsite,"Full-time\nFort Leavenworth, KS\nAbout Us\nTri...","Microsoft Office Suite, Outlook, Word, Excel, ..."

In [4]:
df.columns

Index(['job_title', 'company', 'job_location', 'job_link', 'first_seen',
       'search_city', 'search_country', 'job level', 'job_type', 'job_summary',
       'job_skills'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12894 entries, 0 to 12893
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   job_title       12894 non-null  object
 1   company         12894 non-null  object
 2   job_location    12894 non-null  object
 3   job_link        12894 non-null  object
 4   first_seen      12894 non-null  object
 5   search_city     12894 non-null  object
 6   search_country  12894 non-null  object
 7   job level       12894 non-null  object
 8   job_type        12894 non-null  object
 9   job_summary     12851 non-null  object
 10  job_skills      12705 non-null  object
dtypes: object(11)
memory usage: 1.1+ MB

In [6]:
df.dtypes

job_title         object
company           object
job_location      object
job_link          object
first_seen        object
search_city       object
search_country    object
job level         object
job_type          object
job_summary       object
job_skills        object
dtype: object

In [7]:
df.describe()

,job_title,company,job_location,job_link,first_seen,search_city,search_country,job level,job_type,job_summary,job_skills
count,12894,12894,12894,12894,12894,12894,12894,12894,12894,12851,12705
unique,6797,5283,2446,12894,1,834,4,2,3,11163,12696
top,Business Analyst,ClearanceJobs,United States,https://www.linkedin.com/jobs/data-analyst-jobs,2023-12-20,Hollywood,United States,Mid senior,Onsite,We're looking for an experienced tax professio...,"Microsoft Azure, Microsoft Defender for Cloud,..."
freq,438,238,247,1,12894,150,10386,9691,6670,97,2

In [8]:
df.shape

(12894, 11)

In [9]:
df.nunique().reset_index(name='count')

             index  count
0        job_title   6797
1          company   5283
2     job_location   2446
3         job_link  12894
4       first_seen      1
5      search_city    834
6   search_country      4
7        job level      2
8         job_type      3
9      job_summary  11163
10      job_skills  12696

In [16]:
df.memory_usage(deep=True)

Index                   132
job_title           1094841
company              848117
job_location         857055
job_link            1907488
first_seen           760746
search_city          754991
search_country       792703
job level            757543
job_type             709170
job_summary       135521398
job_skills          4502619
dtype: int64

Handle Missing Values

In [10]:
df.isnull().sum()

job_title           0
company             0
job_location        0
job_link            0
first_seen          0
search_city         0
search_country      0
job level           0
job_type            0
job_summary        43
job_skills        189
dtype: int64

In [44]:
df['job_skills'].fillna('Not Specified', inplace=True)
df['job_summary'].fillna('Not Available', inplace=True)
df.to_csv("Jobs.csv", index=False)
df.head(3)

,job_title,company,job_location,job_link,first_seen,search_city,search_country,job level,job_type,job_summary,job_skills,Year,Month,Day,Month_Name
0,"Data Analyst-SQL, Tableau",Zortech Solutions,"Mountain View, CA",https://www.linkedin.com/jobs/data-analyst-jobs,2023-12-20,Bloomington,United States,Associate,Onsite,Not Available,Not Specified,2023,12,20,December
1,Market Research & Insights Analyst,Indiana University Foundation,"Bloomington, IN",https://www.linkedin.com/jobs/view/market-rese...,2023-12-20,Bloomington,United States,Mid senior,Onsite,Company Description\nAre you a high-performer ...,"Data analysis, Market research, Survey develop...",2023,12,20,December
2,Business Systems Analyst `1,Cook Medical,"Bloomington, IN",https://www.linkedin.com/jobs/view/business-sy...,2023-12-20,Bloomington,United States,Mid senior,Onsite,Overview\nThe Business Systems Analyst 1 perfo...,"Business Analysis, Technical Writing, Software...",2023,12,20,December

Check Duplicates Rows

In [24]:
duplicate_rows=df.duplicated().sum()
print(f"Number of Duplicated Rows : {duplicate_rows}")

Number of Duplicated Rows : 0

Feature Engineering

In [40]:
df.head(1)
df['first_seen']=pd.to_datetime(df['first_seen'])
df['Year']=df['first_seen'].dt.year
df['Month']=df['first_seen'].dt.month
df['Day']=df['first_seen'].dt.day
df['Month_Name']=df['first_seen'].dt.month_name()
df[['first_seen', 'Year', 'Month', 'Day','Month_Name']].head()
df.to_csv("Jobs.csv", index=False)

In [45]:
df.head(3)

,job_title,company,job_location,job_link,first_seen,search_city,search_country,job level,job_type,job_summary,job_skills,Year,Month,Day,Month_Name
0,"Data Analyst-SQL, Tableau",Zortech Solutions,"Mountain View, CA",https://www.linkedin.com/jobs/data-analyst-jobs,2023-12-20,Bloomington,United States,Associate,Onsite,Not Available,Not Specified,2023,12,20,December
1,Market Research & Insights Analyst,Indiana University Foundation,"Bloomington, IN",https://www.linkedin.com/jobs/view/market-rese...,2023-12-20,Bloomington,United States,Mid senior,Onsite,Company Description\nAre you a high-performer ...,"Data analysis, Market research, Survey develop...",2023,12,20,December
2,Business Systems Analyst `1,Cook Medical,"Bloomington, IN",https://www.linkedin.com/jobs/view/business-sy...,2023-12-20,Bloomington,United States,Mid senior,Onsite,Overview\nThe Business Systems Analyst 1 perfo...,"Business Analysis, Technical Writing, Software...",2023,12,20,December

In [53]:
df['Number_of_Skills']=df['job_skills'].str.split(',').str.len()
df['Number_of_Skills'].head(10)

0     1
1    23
2    12
3    36
4    27
5    16
6     1
7     1
8    14
9    14
Name: Number_of_Skills, dtype: int64

In [64]:
df['Remote_Flag']=df['job_type'].map({'Onsite':0,'Remote':1,'Hybrid':2})
df['Remote_Flag'].head(5)
df.to_csv('Jobs.csv',index=False)

In [66]:
df.head(4)

,job_title,company,job_location,job_link,first_seen,search_city,search_country,job level,job_type,job_summary,job_skills,Year,Month,Day,Month_Name,Number_of_Skills,Remote_Flag
0,"Data Analyst-SQL, Tableau",Zortech Solutions,"Mountain View, CA",https://www.linkedin.com/jobs/data-analyst-jobs,2023-12-20,Bloomington,United States,Associate,Onsite,Not Available,Not Specified,2023,12,20,December,1,0
1,Market Research & Insights Analyst,Indiana University Foundation,"Bloomington, IN",https://www.linkedin.com/jobs/view/market-rese...,2023-12-20,Bloomington,United States,Mid senior,Onsite,Company Description\nAre you a high-performer ...,"Data analysis, Market research, Survey develop...",2023,12,20,December,23,0
2,Business Systems Analyst `1,Cook Medical,"Bloomington, IN",https://www.linkedin.com/jobs/view/business-sy...,2023-12-20,Bloomington,United States,Mid senior,Onsite,Overview\nThe Business Systems Analyst 1 perfo...,"Business Analysis, Technical Writing, Software...",2023,12,20,December,12,0
3,Senior VAT and Indirect Tax Analyst,Epic,"Bloomington, IN",https://www.linkedin.com/jobs/view/senior-vat-...,2023-12-20,Bloomington,United States,Mid senior,Onsite,We're looking for an experienced tax professio...,"Accounting, Finance, VAT/GST tax regimes, US a...",2023,12,20,December,36,0